-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_contexts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lead_id uuid NOT NULL UNIQUE,
  business_id uuid NOT NULL,
  system_prompt text NOT NULL DEFAULT ''::text,
  messages_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  gathered_info jsonb NOT NULL DEFAULT '{}'::jsonb,
  conversation_state text NOT NULL DEFAULT 'greeting'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_contexts_pkey PRIMARY KEY (id),
  CONSTRAINT ai_contexts_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT ai_contexts_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id)
);
CREATE TABLE public.businesses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  owner_id uuid NOT NULL,
  name text NOT NULL,
  trade text NOT NULL,
  phone text NOT NULL,
  email text NOT NULL,
  service_area text,
  plan text NOT NULL DEFAULT 'speed-leads'::text CHECK (plan = ANY (ARRAY['speed-leads'::text, 'website'::text, 'compleet'::text])),
  status text NOT NULL DEFAULT 'trialing'::text CHECK (status = ANY (ARRAY['pending_payment'::text, 'trialing'::text, 'active'::text, 'past_due'::text, 'cancelled'::text, 'paused'::text])),
  trial_starts_at timestamp with time zone,
  subscription_ends_at timestamp with time zone,
  stripe_customer_id text UNIQUE,
  stripe_subscription_id text UNIQUE,
  speed_leads_active boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  employees text,
  has_whatsapp boolean DEFAULT false,
  has_website boolean DEFAULT false,
  monthly_leads text,
  calendar_type text CHECK (calendar_type IS NULL OR (calendar_type = ANY (ARRAY['google'::text, 'calendly'::text]))),
  twilio_number text UNIQUE,
  utm_source text,
  utm_medium text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  utm_campaign text,
  utm_term text,
  utm_content text,
  gclid text,
  fbclid text,
  landing_page text,
  referrer text,
  onboarding_step text NOT NULL DEFAULT 'profile'::text,
  onboarding_completed_at timestamp with time zone,
  forwarding_confirmed boolean NOT NULL DEFAULT false,
  available_hours jsonb DEFAULT '{"fri": {"end": "17:00", "start": "08:00"}, "mon": {"end": "17:00", "start": "08:00"}, "sat": null, "sun": null, "thu": {"end": "17:00", "start": "08:00"}, "tue": {"end": "17:00", "start": "08:00"}, "wed": {"end": "17:00", "start": "08:00"}}'::jsonb,
  slot_duration_minutes integer DEFAULT 120,
  max_appointments_per_day integer DEFAULT 4,
  vat_number text,
  address_line1 text,
  postal_code text,
  city text,
  country text DEFAULT 'NL'::text,
  google_review_link text,
  whatsapp_profile_picture_url text,
  whatsapp_profile_picture_handle text,
  whatsapp_personal boolean DEFAULT false,
  website_url text,
  prompt_mode text NOT NULL DEFAULT 'service'::text,
  demo_followup_message text,
  CONSTRAINT businesses_pkey PRIMARY KEY (id),
  CONSTRAINT businesses_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.google_calendar_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  business_id uuid NOT NULL UNIQUE,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  token_expiry timestamp with time zone NOT NULL,
  calendar_id text,
  connected_at timestamp with time zone,
  disconnected_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT google_calendar_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT google_calendar_tokens_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.google_oauth_states (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  state text NOT NULL UNIQUE,
  business_id uuid NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT google_oauth_states_pkey PRIMARY KEY (id),
  CONSTRAINT google_oauth_states_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.leads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  business_id uuid NOT NULL,
  customer_phone text NOT NULL,
  customer_name text,
  source text NOT NULL DEFAULT 'missed_call'::text CHECK (source = ANY (ARRAY['missed_call'::text, 'whatsapp'::text, 'form'::text, 'manual'::text])),
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'qualified'::text, 'appointment_set'::text, 'converted'::text, 'lost'::text, 'archived'::text])),
  inbound_call_sid text,
  conversation_mode text NOT NULL DEFAULT 'ai'::text CHECK (conversation_mode = ANY (ARRAY['ai'::text, 'manual'::text, 'choice_pending'::text])),
  problem_summary text,
  problem_details text,
  address text,
  urgency text CHECK (urgency IS NULL OR (urgency = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'emergency'::text, 'spoed'::text]))),
  first_response_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  appointment_start timestamp with time zone,
  appointment_end timestamp with time zone,
  google_event_id text,
  manual_mode_at timestamp with time zone,
  flagged boolean DEFAULT false,
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  lead_id uuid NOT NULL,
  business_id uuid NOT NULL,
  sender text NOT NULL CHECK (sender = ANY (ARRAY['customer'::text, 'ai'::text, 'owner'::text])),
  body text NOT NULL,
  channel text NOT NULL DEFAULT 'whatsapp'::text CHECK (channel = ANY (ARRAY['whatsapp'::text, 'sms'::text, 'voice'::text])),
  twilio_sid text,
  twilio_status text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id),
  CONSTRAINT messages_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id)
);
CREATE TABLE public.phone_number_pool (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  twilio_number text NOT NULL UNIQUE,
  twilio_sid text NOT NULL,
  meta_phone_number_id text,
  status text NOT NULL DEFAULT 'pending_approval'::text CHECK (status = ANY (ARRAY['pending_approval'::text, 'approved'::text, 'assigned'::text, 'reserved'::text])),
  assigned_business_id uuid,
  assigned_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT phone_number_pool_pkey PRIMARY KEY (id),
  CONSTRAINT phone_number_pool_assigned_business_id_fkey FOREIGN KEY (assigned_business_id) REFERENCES public.businesses(id)
);
